import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Grid from '@mui/material/Grid'
import Head from 'next/head'

const Developer = ()=>{
    return (
        <div>
            <Head>
                <title>Developer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Grid container justifyContent="space-around">
                <Grid item xs={10} md={8}>
                    <div style={{height: '100px'}}></div>
                    <h3 style={{textAlign: 'center', marginBottom: '40px'}}>This App Was Developed Entirely By <b style={{fontSize: '1.2em', color: '#1976D2', cursor: 'pointer'}} onClick={()=>{window.open('https://www.linkedin.com/in/amer-sulaiman/')}}>Amer Sulaiman</b></h3>
                    <pre>
                        <p style={{fontSize: '1.2em', fontWeight: 'bold'}}>The Used Techstack:</p>
                        &nbsp;&nbsp;&nbsp;&nbsp;- React.js/Next.js (For the frontend). 
                        <br />
                        &nbsp;&nbsp;&nbsp;&nbsp;- Flask (For the backend and the API).
                        <br />
                        &nbsp;&nbsp;&nbsp;&nbsp;- SQLite Database.

                        <p style={{fontSize: '1.2em', fontWeight: 'bold'}}>What Does this website do?</p>
                        &nbsp;&nbsp;&nbsp;&nbsp;Do You Want to track Who Opened Your Emails? No Problem, our software creates a very tiny image (1x1) for you called a tracking pixel that you embed in your emails. We will host that pixel for you and it will track when and by who were your emails opened.
                    </pre>
                    

                </Grid>
            </Grid>
            
            <Footer style={{position: 'absolute', bottom: '0', width: '100%'}} />
        </div>
    )
}

export default Developer;