import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Grid from '@mui/material/Grid'
import Button from '@mui/material/Button'

import Link from 'next/Link'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid container direction="column" style={{marginTop: '70px', alignContent: "center"}}>
          <Grid item xs={10} sm={6}>
            <h1 style={{textAlign: 'center'}}>Ready to track your opens?</h1>
          </Grid>
          <Grid item xs={10} sm={6} style={{textAlign: "center", marginTop: '30px'}}>    
            <Link href="/create"><Button variant="outlined" size="large">Create A New Tracking Pixel</Button></Link>
          </Grid>
          <Grid item xs={10} sm={6} style={{textAlign: "center", marginTop: '30px'}}>
            <Link href="/watch"><Button variant="outlined" size="large">Watch Opens</Button></Link>
          </Grid>
          
        </Grid>
      </main>

      
    </div>
  )
}
